### ISSUE TITLE
ros2 topic list only sometimes showing topics

### ISSUE THREAD

**Issue by torbenf** [micro-ROS/micro-ROS_sensors_demo#8]
I'm using foxy on Ubuntu 20.04.
With the help of @altineller on [this](https://github.com/micro-ROS/micro-ROS_sensors_demo/issues/6) and [the other issue](https://github.com/micro-ROS/micro-ROS_sensors_demo/issues/7) I was able to get it to work. Thanks a lot for that =)
Namely I changed the following:
- DEV variable in entrypoint.sh script of the agent to what `ls /dev/serial/by-id/*` gave me
- edited docker-compose.yml and added `privileged: true` to agent service

When I now do a `docker-compose up --build` I see the agent starting up and data being transmitted, e.g.:
```
stiot_agent_1    | [1617786788.116564] debug    | SerialAgentLinux.cpp | send_message             | [** <<SER>> **]        | client_key: 0x5B89F2CA, len: 13, data: 
stiot_agent_1    | 0000: 81 00 00 00 0A 01 05 00 23 0D 00 00 80
stiot_agent_1    | [1617786788.117852] debug    | SerialAgentLinux.cpp | recv_message             | [==>> SER <<==]        | client_key: 0x5B89F2CA, len: 24, data: 
stiot_agent_1    | 0000: 81 80 23 0D 07 01 10 00 0D 2E 00 15 39 B4 48 3D 4C 37 09 BE 96 43 1F 41
stiot_agent_1    | [1617786788.117904] debug    | DataWriter.cpp     | write                    | [** <<DDS>> **]        | client_key: 0x00000001, len: 12, data: 
stiot_agent_1    | 0000: 39 B4 48 3D 4C 37 09 BE 96 43 1F 41
stiot_agent_1    | [1617786788.117950] debug    | SerialAgentLinux.cpp | send_message             | [** <<SER>> **]        | client_key: 0x5B89F2CA, len: 13, data: 
stiot_agent_1    | 0000: 81 00 00 00 0A 01 05 00 24 0D 00 00 80
stiot_agent_1    | [1617786788.119352] debug    | SerialAgentLinux.cpp | recv_message             | [==>> SER <<==]        | 
``` 
### **however**
- _somtimes_ the topics aren't listed when I look into the agent container with `docker exec -it micro-ros_sensors_demo_stiot_agent_1 bash` and do a `ros2 topic list`
and rqt obviously doesn't start up (as it is waiting for the topics to be present)

- _sometimes_  the topics are present in the agent container, rqt starts up but shows not data. The topics aren't present in the rqt container

- _sometimes_ the topics are present in both containers, rqt starts up, but doesn't show data AND no legend at all (like /sensors/imu//x), restarting the board via the reset button does not help.

- _sometimes_ the topics are present in both containers, rqt starts up, but doesn't show data BUT the legend is there. A simple press of the reset button on the board and data s coming in.

- _sometimes_ everything works, rqt starts up and shows data

All I'm doing between two runs with different outcomes is CTRL + c to stop the containers, wait for them to stop and then pressing the restart button on the board and doing a `docker-compose up --build` again.

----

While writing this I noticed, that I can do the following to get it to work more reliable.
1. After doing the changes described above and rebuilding the containers Ido a `docker-compose up -d`
2. If rqt doesn't start up press reset button on board and wait for rqt to show up 
3. If rqt starts up but doesn't show data just close rqt and do a `docker-compose up -d` again

I can live with this behavior, especially because it's just a demo, but wanted to leave this here so others may struggle less.
Regards

**Comment by pablogs9** [comment]
Hello @torbenf can you PR the `privileged: true` changes to this repo?
